# Generated by Django 3.1.4 on 2022-05-09 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220509_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='inital-slug', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 16, 2, 8, 2025)),
        ),
    ]
