# Generated by Django 3.1.4 on 2022-05-03 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220503_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 17, 11, 48, 690334)),
        ),
    ]
